config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notifications, only: [:index, :show, :destroy]
  resources :trips, only: [:index, :new, :create, :show, :update, :destroy] do
    member do
      get 'review'
    end
  end

  get 'trips/details/info', to: 'trips#info'
  get 'my_trips', to: 'trips#mytrips'
  get 'vercam', to: 'vercam#vercam'
  get 'sankey', to: 'trips#sankey'
  
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :origin_destination_routes, class_name: 'OriginDestinationRoute'
  # validates :date, uniqueness: { scope: [:user] }

  DEPARTURE_TIME = %w[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

  after_create :call_flater

  private

  def call_flater
    if self.user.id != 1
      FlaterJob.perform_later(self.user.id)
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @trip = Trip.new()
  end

  def new
    @trip = Trip.new()
    raise
  end

  def update
    @trip = Trip.find(params[:id])
    original_time = @trip.time
    new_time = params[:trip]["time"].to_f
    @trip.origin_destination_routes.routes.each do |route|

      road_original_time = original_time.to_i + (route.step.to_i - 1)
      road_new_time = new_time.to_i + (route.step.to_i - 1)

      road_car = RoadCar.where("road_id = #{route.road.id} and time = #{road_original_time}").first
      road_car.number_of_cars -= 1
      road_car.save

      new_road_car = RoadCar.where("road_id = #{route.road.id} and time = #{road_new_time}").first
      new_road_car.number_of_cars += 1
      new_road_car.save
    end
    # raise
    @trip.time = params[:trip]["time"].to_f
    # raise
    actual_duration = params[:trip]['actual_duration(4i)'].to_i*60 + params[:trip]['actual_duration(5i)'].to_i
    @trip.actual_duration = actual_duration
    @trip.save
    redirect_to my_trips_path, notice: "trip succesfully updated!"
  end

  def create
    @year = params[:trip]["date(1i)"]
    @month = params[:trip]["date(2i)"]
    @day = params[:trip]["date(3i)"]
    @odr = OriginDestinationRoute.find(params[:trip]["origin_destination_routes"])
    date = DateTime.new(@year.to_i, @month.to_i, @day.to_i).to_date
    if Trip.where("user_id = #{current_user.id} and date = '#{date}'").count > 0
      flash[:notice] = 'You already have a planned trip for this date.'
      redirect_to my_trips_path and return
    end
    trip = Trip.new(trip_params)
    trip.origin_destination_routes = @odr
    trip.date = date
    trip.user = current_user
    if trip.save
      #Salvar a viagem de carro
      @odr.routes.each do |route|
        time = params[:trip]['time'].to_i + (route.step.to_i - 1)
        road_car = RoadCar.where("road_id = #{route.road.id} and time = '#{time}'").first
        road_car.number_of_cars += 1
        road_car.save
      end
      redirect_to my_trips_path
    else
      # flash.now[:alert] = 'Failed!'
      # redirect_to trips_info_path(:params[:trip])
    end
  end

  def info
    # raise
    if params[:new_trip].nil? || params[:new_trip]['day'] == ''
      redirect_to trips_path, alert: 'Invalid parameters. Please fill all fields'
    else
      @origin = params[:new_trip][:origin]
      @destination = params[:new_trip][:destination]
      # @year = params[:new_trip]["day(1i)"]
      # @month = params[:new_trip]["day(2i)"]
      # @day = params[:new_trip]["day(3i)"]
      @date = params[:new_trip]['day']
      # raise
      horarios = %w[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
      roads_hash = {}
      @origin_destination_routes = OriginDestinationRoute.where("origin_id = #{@origin} and destination_id = #{@destination}")
      Road.all.each do |road|
        horario_hash = {}
        horarios.each do |horario|
          road_cars = RoadCar.where("time = '#{horario}' and road_id = #{road.id}").first
          horario_hash[horario] = road_cars.number_of_cars
        end
        roads_hash[road.name] = horario_hash
      end
      @graph_data = roads_hash
      gon.graph_data = @graph_data
      # raise
      @trip = Trip.new()
      @trip.date = @date


    @sankey_graph_data = []
    OriginDestinationRoute.all.each do |odr|
      i = 1
      weight = Trip.all.where("origin_destination_routes_id = #{odr.id}").count
      until (odr.routes.where("step = #{i}")).empty?
        step1 = odr.routes.where("step = #{i}").first.road.name
        if (odr.routes.where("step = #{i+1}")).empty?
          step2 = 'Ubatuba'
        else
          step2 = odr.routes.where("step = #{i + 1}").first.road.name
        end
        array = [step1, step2, weight]
        @sankey_graph_data << array
        i += 1
      end
    end
    gon.sankey_graph_data = @sankey_graph_data
    # raise
    end
  end

  def show
    @trip = Trip.find(params[:id])
    # raise
    if @trip.user != current_user
      redirect_to my_trips_path, alert: 'you don\'t have permission'
    end
    @origin = @trip.origin_destination_routes.origin
    @destination = @trip.origin_destination_routes.destination
    @year = @trip.date.year
    @month = @trip.date.month
    @day = @trip.date.day
    horarios = %w[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    roads_hash = {}
    @odr = @trip.origin_destination_routes
    routes_hash = {}

    @odr.roads.each do |road|
      step = @trip.origin_destination_routes.routes.where("road_id = #{road.id}").first.step
      cars = road.road_cars.where("time = #{@trip.time + (step - 1)}").first.number_of_cars
      roads_hash[road.name] = cars


      horario_hash = {}
      horarios.each do |horario|
        road_cars = RoadCar.where("time = '#{horario}' and road_id = #{road.id}").first
        horario_hash[horario] = road_cars.number_of_cars
      end
      routes_hash[road.name] = horario_hash
    end
    @graph_data_routes = routes_hash
    @graph_data = roads_hash
    gon.time = @trip.time.to_i
    gon.graph_data = @graph_data

    gon.graph_data_routes = @graph_data_routes
    # raise
  end

  def mytrips
    @trips = Trip.all.where("user_id = #{current_user.id}")
  end


  def destroy
    @trip = Trip.find(params[:id])
    @trip.delete
    redirect_to my_trips_path, alert: 'trip cancelled!'
  end

  def review
    @trip = Trip.find(params[:id])
    if @trip.user != current_user
      redirect_to my_trips_path, alert: 'you don\'t have permission'
    end
  end


  def sankey
    @graph_data = []
    OriginDestinationRoute.all.each do |odr|
      i = 1
      weight = Trip.all.where("origin_destination_routes_id = #{odr.id}").count

      # origin = odr.origin.name
      # first_step  = odr.routes.where("step = 1").first.road.name
      # @graph_data << [origin, first_step, weight]

      until (odr.routes.where("step = #{i}")).empty?
        step1 = odr.routes.where("step = #{i}").first.road.name
        if (odr.routes.where("step = #{i+1}")).empty?
          step2 = 'Ubatuba'
        else
          step2 = odr.routes.where("step = #{i + 1}").first.road.name
        end
        array = [step1, step2, weight]
        @graph_data << array
        i += 1
      end
    end
    gon.graph_data = @graph_data
    # raise
  end

  private

  def trip_params
    params.require(:trip).permit(:time, "date(1i)", "date(2i)", "date(3i)")
  end
end

app/views/trips/index.html.erb
<div class="navbar-absolute">
  <%= render "shared/tvnavbar" %>
</div>
<div class="new-viagem">
  <div class="container justify-content-center">
    <div class="row justify-content-center">
      <div class="col-sm-7" id="form-box">
        <h2 class="trip-input-1 fade show pb-3">Where are you?</h2>
        <%= simple_form_for :new_trip, url: trips_details_info_path, method: :get, required: true do |o| %>
          <div class="py-1 trip-input-1 fade show"><%= o.input :origin, collection: Origin.all, label: false%></div>
        <h2 class="trip-input-2 fade show pb-3">Where are you going?</h2>
          <div class="py-1 trip-input-2 fade show "><%= o.input :destination, collection: Destination.all, label: false %></div>
        <h2 class="trip-input-3 fade show pb-3">When do you plan on leaving?</h2>
          <div class="pt-1 trip-input-3"><%=o.input :start_date, as: :date, html5: true%></div>
          

          <div class="d-flex justify-content-center trip-submit"><%= o.submit 'Check Routes', class: 'btn m-4'%></div>
        <% end%>
        <div class="next-button text-end"><span>next</span></div>
        <i class="fas fa-info" data-bs-container="body" data-bs-toggle="popover"  data-bs-trigger="hover focus" data-bs-placement="right" data-bs-content="Tell us your trip route and we'll give you a prediction of the roads' traffic!"></i>
      </div>
    </div>
  </div>
</div>

app/views/trips/info.html.erb
<div class="navbar-absolute">
  <%= render "shared/tvnavbar" %>
</div>
<div class="container clima">
  <div class="row" style='width: 100%;'>
    <div class="col-12" style='width: 100%; padding: 0;'>
      <div class="card mb-5">
        <div class="card-category" data-trip-date="<%=params[:new_trip][:day]%> ">
          <div class='pe-3'>
            <h1>Weather in <span id="city"></span></h1>
            <h2 id="description"></h2>
            <div>
              <div class="d-flex justify-content-end pe-3">
                <img src="" alt="" id="icon">
                <h2 id="temperature"></h2>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="info-content">
  <div class="container">
    <h1 class="text-center pb-3" style='font-family: "Cairo", sans-serif;'> Which route do you wanna take?</h1>
    <div class="d-flex justify-content-center pt-4 pb-5">
      <div id="sankey_multiple" style=" height: 300px;"></div>
    </div>
    <div class="text-center">
      <% @origin_destination_routes.each do |odr| %>
        <div class="chart-box" data-route = "<%=odr.name%>">
          <div class="routes">
            <h2 class="text-center route-title" data-road-destination = "<%=odr.id%>"><%= odr.name %></h2>
            <div class="charts-flex">
              <% @graph_data.each do |key, value| %>
                <% roads = []  %>
                <% odr.roads.each do |road| roads << road.name end%>
                <% if roads.include? key.to_s  %>
                  <div class="gchart-box">
                    <div class="gchart chart_div_<%=key.to_s%> m-4 d-none" data-road-destination = "<%=odr.id%>"></div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="new-trip-form fade d-flex align-items-center pt-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-sm-7">
          <h1 class="text-center" style='font-family: "Cairo", sans-serif;'>Choose your road options and departure time</h1>
          <div class="mb-4">
            <%= simple_form_for @trip do |f| %>
              <%= f.input :origin_destination_routes, collection: @origin_destination_routes, label: 'Route' %>
              <%= f.input :time, label: 'Departure Time', collection: Trip::DEPARTURE_TIME%>
              <%= simple_fields_for :fake do |o|  %>
                <%= o.input :departure, as: :string, disabled: true, label: 'Departure Date',  input_html: { class:'datepicker' }, input_html: { value: @trip.date} %>
              <% end %>
              <div class="d-none">
                <%= f.input :date, readonly: true%>
              </div>
              <div class=" d-flex justify-content-center">
                <div class="form-actions btn mt-4">
                  <%= f.button :submit, 'Create Trip' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



    <script type="text/javascript">

     const routeOptions = document.querySelectorAll('.routes')

      routeOptions.forEach((route) => {
        let title = route.querySelector('h2')
        let graphs = route.querySelectorAll('.gchart')
        title.addEventListener('click', (event) => {
          graphs.forEach(graph => {
            graph.classList.toggle('d-none');
            drawChart();
          });
        })
      });

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      // google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        for (var road in gon.graph_data) {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Hours');
        data.addColumn('number', 'cars');
        data_array = [];
        graph_data = gon.graph_data[road];
        for (var key in graph_data) {
          array = [key, graph_data[key]];
          data_array.push(array);
        }
        data.addRows(data_array);


        // Set chart options
        var options = {'title':road,
                       'width':500,
                       'height':300,
                       'colors':['#3A4257'],
                       'backgroundColor':'#e8e6f2',
                        vAxis: {
                          gridlines: {
                            color: 'transparent',
                            interval: 0
                          }
                        },
                        animation: {
                          startup: true,
                          duration: 3000
                        }
        }

        const departureTime = document.querySelector('#trip_time');
        const routeForm = document.querySelector('#trip_origin_destination_routes');

        elements = document.querySelectorAll(`.chart_div_${road}`)

        elements.forEach(element => {
          let originDestinationRoad = element.dataset.roadDestination
          var chart = new google.visualization.ColumnChart(element);

          function selectHandler() {
          var selectedItem = chart.getSelection()[0];
            if (selectedItem) {
              var horario = data.getValue(selectedItem.row, 0);
              // alert('The user selected ' + horario);
              departureTime.value = horario;
              routeForm.value = originDestinationRoad
            }
          }

          google.visualization.events.addListener(chart, 'select', selectHandler);
          chart.draw(data, options)
        });
        }
      }

    </script>


<script type="text/javascript">
  google.charts.load("current", {packages:["sankey"]});
  google.charts.setOnLoadCallback(drawSankeyChart);
   function drawSankeyChart() {
    var data_sankey = new google.visualization.DataTable();
    data_sankey.addColumn('string', 'From');
    data_sankey.addColumn('string', 'To');
    data_sankey.addColumn('number', 'Weight');
    data_sankey.addRows(gon.sankey_graph_data);

    // Set chart options
    var options = {
      width: 600,
      sankey: { node: { nodePadding: 150 } },

    };

    // Instantiate and draw our chart, passing in some options.
    var sankey_chart = new google.visualization.Sankey(document.getElementById('sankey_multiple'));
    sankey_chart.draw(data_sankey, options);
   }
</script>

app/views/trips/mytrips.html.erb
<div class="navbar-absolute">
  <%= render "shared/tvnavbar" %>
</div>
<div class="container">
<h1 class="text-center py-3" style='font-size: 60px;'>My Trips</h1>
  <div class="trips-flex">
    <% @trips.where("date >= '#{Date.today}'").each do |trip| %>
      <div class="trip-card">
        <h2 class='text-center pt-3'><%= trip.origin_destination_routes.name %></h2>
        <%# <div class="d-flex justify-content-around py-3"> %>
          <p class="mb-1 ml-2">Origin: <%= trip.origin_destination_routes.origin.name %></p>
          <p class="mb-1 ml-2">Destination: <%= trip.origin_destination_routes.destination.name  %></p>
          <p class="mb-1 ml-2">Date: <%= trip.date %></p>
          <p class = 'ml-2'>Departure Time: <%= "#{trip.time.to_i}h" %></p>
        <%# </div> %>
        <div class="d-flex justify-content-around pb-3">
          <%= link_to 'check trip', trip_path(trip) %>
          <%= link_to 'cancel trip', trip_path(trip), method: :delete, data: {confirm: "Are you sure?"}, remote: true  %>
        </div>
      </div>
    <% end  %>
  </div>
<h1 class="text-center py-3" style='font-size: 60px;'>Past Trips</h1>
  <div class="trips-flex">
    <% @trips.where("date < '#{Date.today.to_date}'").each do |trip| %>
      <div class="trip-card">
        <h2 class='text-center pt-3'><%= trip.origin_destination_routes.name %></h2>
        <%# <div class="d-flex justify-content-around py-3"> %>
          <p class="mb-1 ml-2">Origin: <%= trip.origin_destination_routes.origin.name %></p>
          <p class="mb-1 ml-2">Destination: <%= trip.origin_destination_routes.destination.name  %></p>
          <p class="mb-1 ml-2">Date: <%= trip.date %></p>
          <p class = 'ml-2'>Departure Time: <%= "#{trip.time.to_i}h" %></p>
        <%# </div> %>
        <div class="d-flex justify-content-around pb-3">
          <%= link_to 'review trip', review_trip_path(trip) %>
        </div>
      </div>
    <% end  %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="new-viagem">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-sm-7">
        <h1>New Trip</h1>
        <%= simple_form_for @trip do |f| %>
          <%= simple_fields_for :other do |o| %>
            <div class="py-1"><%= o.input :origin, collection: Origin.all %></div>
            <div class="py-1"><%= o.input :destination, collection: Destination.all %></div>
          <% end%>
          <div class="pt-1 pb-5"><%= f.input :date %></div>
          <div class="d-flex justify-content-center"><%= f.submit class: 'btn'%></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/review.html.erb
<div class="navbar-absolute">
  <%= render "shared/tvnavbar" %>
</div>

<div class="container trip-review">
  <h1 class="text-center mt-4">Trip Review</h1>
  <div class="row justify-content-md-center">
    <div class="col-sm-7" id="form-box">
      <%= simple_form_for @trip do |f| %>
        <%= f.input :date, as: :string, input_html: { class:'flex-grow-1 datepicker' }%>
        <%= f.input :time, label: 'Departure Time', collection: Trip::DEPARTURE_TIME, input_html: { class:'flex-grow-1' }%>
        <%= f.input :actual_duration, label: 'Actual trip duration', as: :time %>
        <div class="d-flex justify-content-center"><%= f.submit class: 'btn'%></div>
      <% end  %>
        <i class="fas fa-info" data-bs-container="body" data-bs-toggle="popover"  data-bs-trigger="hover focus" data-bs-placement="right" data-bs-content="With this data, we can work on make better estimations for your trip times!"></i>
 </div>
  </div>
</div>

app/views/trips/sankey.html.erb
<h1>hello</h1>
<div class="container">

  <div id="sankey_multiple" style="height: 300px;"></div>

</div>

<script type="text/javascript">
  google.charts.load("current", {packages:["sankey"]});
  google.charts.setOnLoadCallback(drawChart);
   function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'From');
    data.addColumn('string', 'To');
    data.addColumn('number', 'Weight');
    data.addRows(gon.graph_data);

    // Set chart options
    var options = {
      width: 600,
      sankey: { node: { nodePadding: 10 }, iterations: 100 },
    };

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.Sankey(document.getElementById('sankey_multiple'));
    chart.draw(data, options);
   }
</script>

app/views/trips/show.html.erb
<div class="navbar-absolute">
  <%= render "shared/tvnavbar" %>
</div>

<div class="container">
  <div class="text-center pt-3">
    <h2 class="text-center">Route: <%= @odr.name %></h2>
    <h2 class="text-center">Departure time: <%= @trip.time.to_i %>h</h2>
    <div class="charts-flex justify-content-center">
    <div class="gchart-box">
      <div class="gchart chart_div m-4"></div>
    </div>
  </div>
</div>


<div class="text-center">
  <div class="chart-box" data-route = "<%=@odr.name%>">
  <div class="routes">
    <h2 class="text-center route-title check-roads" data-road-destination = "<%=@odr.id%>">Check road status</h2>
    <div class="charts-flex justify-content-center">
      <% @graph_data_routes.each do |key, value| %>
      <% roads = []  %>
      <% @odr.roads.each do |road| roads << road.name end%>
        <% if roads.include? key.to_s  %>
        <div class="gchart-box">
            <div class="gchart road chart_div_<%=key.to_s%> m-4 d-none" data-road-destination = "<%=@odr.id%>"></div>
        </div>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>




<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-3">
      <h2 class="text-center">Update your trip</h2>
      <%= simple_form_for @trip do |f| %>
        <%= f.input :time, collection: Trip::DEPARTURE_TIME, label: 'Departure Time' %>
        <div class="text-center">
        <%= f.submit class: 'button-light' %>
        </div>
      <% end  %>
    </div>
  </div>
</div>


    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart(option = 'all') {

        // Create the data table.
        // var data = new google.visualization.DataTable();
        // data.addColumn('string', 'Topping');
        // data.addColumn('number', 'Slices');
        // data.addColumn('number', 'Test');
        // data.addRows([
        //   ['Mushrooms', 3,3],
        //   ['Onions', 1,3],
        //   ['Olives', 1,3],
        //   ['Zucchini', 1,3],
        //   ['Pepperoni', 2,3]
        // ])

        if (option != 'onlyRoad') {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'hour');
        data.addColumn('number', 'Cars' );
        data.addColumn({ role: 'annotation' })
        data_array = [];
        graph_data = gon.graph_data;
        let i = 0
        for (var key in graph_data) {
          array = [String(gon.time + i) + 'h', graph_data[key], key];
          data_array.push(array);
          i++;
        }
        // console.log(data_array)
        data.addRows(data_array);
        // console.log(data)

        // Set chart options
        var options = {'title': 'Your Trip',
                       'width':500,
                       'height':300,
                       'colors':['#3A4257'],
                       'backgroundColor':'#e8e6f2',
                        vAxis: {
                           gridlines: {
                               color: 'transparent',
                               interval: 1
                           }
                       },
                      animation: {
                      startup: true,
                      duration: 3000
                        }
        }

        elements = document.querySelectorAll(`.chart_div`)
        elements.forEach(element => {
          var chart = new google.visualization.ColumnChart(element);
          chart.draw(data, options)
        });


      }


       for (var road in gon.graph_data_routes) {
        // console.log(road)
        var data_routes = new google.visualization.DataTable();
        data_routes.addColumn('string', 'Hours');
        data_routes.addColumn('number', 'cars');
        data_routes_array = [];
        graph_data_routes = gon.graph_data_routes[road];
        for (var key in graph_data_routes) {
          array = [key, graph_data_routes[key]];
          data_routes_array.push(array);
        }
        data_routes.addRows(data_routes_array);


        // Set chart options
        var options = {'title':road,
                       'width':500,
                       'height':300,
                       'colors':['#3A4257'],
                       'backgroundColor':'#e8e6f2',
                        vAxis: {
                          gridlines: {
                            color: 'transparent',
                            interval: 0
                          }
                        },
                        animation: {
                          startup: true,
                          duration: 3000
                        }
        }

        const departureTime = document.querySelector('#trip_time');
        const routeForm = document.querySelector('#trip_origin_destination_routes');

        elements = document.querySelectorAll(`.chart_div_${road}`)

        elements.forEach(element => {
          let originDestinationRoad = element.dataset.roadDestination
          var chart = new google.visualization.ColumnChart(element);
          chart.draw(data_routes, options)
        });
        }


        const checkRoadsButton = document.querySelector(".check-roads")
        let graphs = document.querySelectorAll('.gchart.road')
        checkRoadsButton.addEventListener('click', (event) => {
                  graphs.forEach(graph => {
            graph.classList.toggle('d-none');
            drawChart('onlyRoad');
          });

        })
      }
    </script>