config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notifications, only: [:index, :show, :destroy]
  resources :trips, only: [:index, :new, :create, :show, :update, :destroy] do
    member do
      get 'review'
    end
  end

  get 'trips/details/info', to: 'trips#info'
  get 'my_trips', to: 'trips#mytrips'
  get 'vercam', to: 'vercam#vercam'
  get 'sankey', to: 'trips#sankey'
  
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-secondary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!--<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://images.unsplash.com/photo-1494783367193-149034c05e8f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>-->

app/views/shared/_tvnavbar.html.erb
<div class='text-right tvnavbar'>
  <% if user_signed_in? %>
    <%= link_to 'new trip', trips_path %>
    <%= link_to  'my trips', my_trips_path %>
    <%= link_to 'log out', destroy_user_session_path, method: :delete  %>
    <i class="btn fas fa-bell sino" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"></i>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
      <div class="offcanvas-header">
        <i type="button" class="fas fa-angle-left volta" data-bs-dismiss="offcanvas" aria-label="Close"></i>
        <h5 id="offcanvasRightLabel">Notifications</h5>
      </div>
      <div class="offcanvas-body">
        <% current_user.notifications.each do |notification| %>
        <div class="card">
          <p><%= notification.params[:message] %></p>
          <%= link_to notification.params[:link], notification.params[:url] %>
        </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <%= link_to 'new trip', trips_path %>
    <%= link_to 'login', new_user_session_path %>
    <%= link_to 'sign up', new_user_registration_path %>
  <% end  %>
</div>